db:
  uri: "mongodb://root:example@localhost:27017"
  name: "crawler_db"

gutenberg:
  min_id: 1
  max_id: 77034
  docs_collection: "gutenberg_docs"
  queue_collection: "gutenberg_queue"

standardebooks:
  docs_collection: standardebooks_docs
  queue_collection: standardebooks_queue
  seed: "https://standardebooks.org/"
  allowed_regex: r'^https://standardebooks\.org/.*text/single-page$'



logic:
  delay: 1
  recheck_interval: 86400
